//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballLinkApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Club()
        {
            this.Match = new HashSet<Match>();
            this.Match1 = new HashSet<Match>();
        }
    
        public int ClubId { get; set; }
        public Nullable<int> ClubRank { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> ClothingID { get; set; }
        public string ClubDescription { get; set; }
        public Nullable<int> MatchCount { get; set; }
        public Nullable<int> WinCount { get; set; }
        public Nullable<int> DrawCount { get; set; }
        public Nullable<int> LoseCount { get; set; }
        public Nullable<int> Points { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match1 { get; set; }
    }
}
